name: CI

on: [pull_request]

jobs:
  build:

    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v1
    - name: Xcode Version
      run: xcodebuild -version
    - name: Build
      run: xcodebuild test -project Pipeline.xcodeproj -scheme PipelineTests -destination "platform=iOS Simulator,OS=12.2,name=iPhone XS"
